version: '3.8'
services:
  portfolio:
    container_name: christian_portfolio_container
    image: christian_portfolio_img
    build:
      context: .
      dockerfile: Dockerfile # (optional if file is named 'Dockerfile')
    ports:
      - "3000:80"
    restart: unless-stopped
