apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: resume-site
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: NodePort
  selector:
    app: resume
  ports:
    - port: 80
      targetPort: 4173
      nodePort: 30080

