apiVersion: apps/v1
kind: Deployment
metadata:
  name: christian-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: christian-portfolio
  template:
    metadata:
      labels:
        app: christian-portfolio
    spec:
      containers:
      - name: portfolio-container
        image: christian_portfolio_img
        ports:
        - containerPort: 80

