FROM jenkins/jenkins:lts

USER root

# Add Jenkins user to existing group (GID 20) — usually 'staff' on macOS
RUN usermod -aG staff jenkins

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs docker.io

USER jenkins


